name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install PyTorch (CPU)
        run: |
          python -m pip install --upgrade pip
          pip install "torch==2.2.*" --index-url https://download.pytorch.org/whl/cpu

      - name: Install PyG (CPU wheels matched to Torch 2.2)
        run: |
          pip install "torch-geometric>=2.5,<3.0"
          pip install "torch-scatter>=2.1,<3.0" "torch-sparse>=0.6,<1.0" \
                      "torch-cluster>=1.6,<2.0" "torch-spline-conv>=1.2,<2.0" \
                      -f https://data.pyg.org/whl/torch-2.2.0+cpu.html

      - name: Install other deps
        run: |
          pip install numpy scipy scikit-learn networkx matplotlib pytest

      - name: Run tests
        run: pytest -q
